### ISSUE TITLE
Why encrypt?

### ISSUE THREAD

**Issue by Jwink3101** [renard/papersave#1]
Maybe this can be added to the FAQ, but why add the gpg encryption given that you also include the password? Seems like it adds unnecessary overhead. What as your motivation?

**Comment by renard** [comment]
Hi,

First this project is still young and design not yet finished.

Now the goal of papersave is to keep a hardcopy of sensitive data in a safe (I really mean a REAL safe). If you need to recover your data you can still type them manually or use the QR-codes. If you don't have a QR-code reader, you may want to be able to use an online QR-code processor or an app on your phone. This method is really unsafe since you don't know what happens to your data. The encryption here is only used to prevent tier QR-Code processor to grab your data. The reason why the password is printed, is that you really want to be able to decipher the data on it.

Don't forget this is a last resort data recovery.
